DROP TABLE IF EXISTS query_checks;
CREATE TABLE query_checks AS
SELECT 'Q01' check_id, 'candidate rows' check_name, '1597' expected, CAST(COUNT(*) AS TEXT) actual, CASE WHEN COUNT(*) = 1597 THEN 'pass' ELSE 'fail' END status FROM candidate_release
UNION ALL SELECT 'Q02', 'unique candidate tracts', '1597', CAST(COUNT(DISTINCT tract_fips) AS TEXT), CASE WHEN COUNT(DISTINCT tract_fips) = 1597 THEN 'pass' ELSE 'fail' END FROM candidate_release
UNION ALL SELECT 'Q03', 'candidate counties', '14', CAST(COUNT(DISTINCT county_fips) AS TEXT), CASE WHEN COUNT(DISTINCT county_fips) = 14 THEN 'pass' ELSE 'fail' END FROM candidate_release
UNION ALL SELECT 'Q04', 'accepted public release', '1', CAST(COUNT(DISTINCT public_source_release) AS TEXT), CASE WHEN COUNT(DISTINCT public_source_release) = 1 AND MIN(public_source_release) = 'CDC PLACES 2025 census-tract release' THEN 'pass' ELSE 'fail' END FROM candidate_release
UNION ALL SELECT 'Q05', 'fictional synthetic release', '1', CAST(COUNT(DISTINCT synthetic_source_id) AS TEXT), CASE WHEN COUNT(DISTINCT synthetic_source_id) = 1 AND MIN(synthetic_flag) = 1 AND MAX(synthetic_flag) = 1 THEN 'pass' ELSE 'fail' END FROM candidate_release
UNION ALL SELECT 'Q06', 'public modeled estimates retained', '1597', CAST(SUM(modeled_crude_prevalence_percent IS NOT NULL) AS TEXT), CASE WHEN SUM(modeled_crude_prevalence_percent IS NOT NULL) = 1597 THEN 'pass' ELSE 'fail' END FROM candidate_release
UNION ALL SELECT 'Q07', 'limited-support rows retained', '49', CAST(SUM(support_state = 'limited_support_review') AS TEXT), CASE WHEN SUM(support_state = 'limited_support_review') = 49 THEN 'pass' ELSE 'fail' END FROM candidate_release
UNION ALL SELECT 'Q08', 'declared rules', '4', CAST(COUNT(DISTINCT rule_id) AS TEXT), CASE WHEN COUNT(DISTINCT rule_id) = 4 THEN 'pass' ELSE 'fail' END FROM rule_assignments
UNION ALL SELECT 'Q09', 'assignment rows', '6388', CAST(COUNT(*) AS TEXT), CASE WHEN COUNT(*) = 6388 THEN 'pass' ELSE 'fail' END FROM rule_assignments
UNION ALL SELECT 'Q10', 'unique rule-tract assignments', '6388', CAST(COUNT(DISTINCT rule_id || tract_fips) AS TEXT), CASE WHEN COUNT(DISTINCT rule_id || tract_fips) = 6388 THEN 'pass' ELSE 'fail' END FROM rule_assignments
UNION ALL SELECT 'Q11', 'candidate rows per rule', '1597 each', CAST(MIN(candidate_rows) AS TEXT) || ' to ' || CAST(MAX(candidate_rows) AS TEXT), CASE WHEN MIN(candidate_rows) = 1597 AND MAX(candidate_rows) = 1597 THEN 'pass' ELSE 'fail' END FROM rule_reconciliation
UNION ALL SELECT 'Q12', 'selected tracts per rule', '28 each', CAST(MIN(selected_tracts) AS TEXT) || ' to ' || CAST(MAX(selected_tracts) AS TEXT), CASE WHEN MIN(selected_tracts) = 28 AND MAX(selected_tracts) = 28 THEN 'pass' ELSE 'fail' END FROM rule_reconciliation
UNION ALL SELECT 'Q13', 'allocated places per rule', '280 each', CAST(MIN(allocated_places) AS TEXT) || ' to ' || CAST(MAX(allocated_places) AS TEXT), CASE WHEN MIN(allocated_places) = 280 AND MAX(allocated_places) = 280 THEN 'pass' ELSE 'fail' END FROM rule_reconciliation
UNION ALL SELECT 'Q14', 'partial awards', '0', CAST(SUM(selected = 1 AND allocated_places != 10) + SUM(selected = 0 AND allocated_places != 0) AS TEXT), CASE WHEN SUM(selected = 1 AND allocated_places != 10) + SUM(selected = 0 AND allocated_places != 0) = 0 THEN 'pass' ELSE 'fail' END FROM rule_assignments
UNION ALL SELECT 'Q15', 'automatic actions', '0', CAST(SUM(automatic_action) AS TEXT), CASE WHEN SUM(automatic_action) = 0 THEN 'pass' ELSE 'fail' END FROM rule_assignments
UNION ALL SELECT 'Q16', 'equal-rule county rows', '14', CAST(COUNT(*) AS TEXT), CASE WHEN COUNT(*) = 14 THEN 'pass' ELSE 'fail' END FROM county_concentration WHERE rule_id = 'equal_geographic'
UNION ALL SELECT 'Q17', 'equal awards per county', '2 each', CAST(MIN(selected_tracts) AS TEXT) || ' to ' || CAST(MAX(selected_tracts) AS TEXT), CASE WHEN MIN(selected_tracts) = 2 AND MAX(selected_tracts) = 2 THEN 'pass' ELSE 'fail' END FROM county_concentration WHERE rule_id = 'equal_geographic'
UNION ALL SELECT 'Q18', 'need rule selected tracts', '28', CAST(SUM(selected) AS TEXT), CASE WHEN SUM(selected) = 28 THEN 'pass' ELSE 'fail' END FROM rule_assignments WHERE rule_id = 'need_based'
UNION ALL SELECT 'Q19', 'capacity rule selected tracts', '28', CAST(SUM(selected) AS TEXT), CASE WHEN SUM(selected) = 28 THEN 'pass' ELSE 'fail' END FROM rule_assignments WHERE rule_id = 'capacity_aware'
UNION ALL SELECT 'Q20', 'community rule selected tracts', '28', CAST(SUM(selected) AS TEXT), CASE WHEN SUM(selected) = 28 THEN 'pass' ELSE 'fail' END FROM rule_assignments WHERE rule_id = 'community_review'
UNION ALL SELECT 'Q21', 'capacity rule minimum capacity', '0 invalid', CAST(SUM(selected = 1 AND fictional_capacity_places < 10) AS TEXT), CASE WHEN SUM(selected = 1 AND fictional_capacity_places < 10) = 0 THEN 'pass' ELSE 'fail' END FROM rule_assignments WHERE rule_id = 'capacity_aware'
UNION ALL SELECT 'Q22', 'community readiness requirements', '0 invalid', CAST(SUM(selected = 1 AND (fictional_capacity_places < 10 OR fictional_community_review_state != 'ready_for_planning_review' OR fictional_objection_state != 'no_recorded_objection' OR fictional_language_access_ready != 1 OR fictional_disability_access_ready != 1)) AS TEXT), CASE WHEN SUM(selected = 1 AND (fictional_capacity_places < 10 OR fictional_community_review_state != 'ready_for_planning_review' OR fictional_objection_state != 'no_recorded_objection' OR fictional_language_access_ready != 1 OR fictional_disability_access_ready != 1)) = 0 THEN 'pass' ELSE 'fail' END FROM rule_assignments WHERE rule_id = 'community_review'
UNION ALL SELECT 'Q23', 'community county maximum', '<=3', CAST(MAX(selected_tracts) AS TEXT), CASE WHEN MAX(selected_tracts) <= 3 THEN 'pass' ELSE 'fail' END FROM county_concentration WHERE rule_id = 'community_review'
UNION ALL SELECT 'Q24', 'rule summaries', '4', CAST(COUNT(*) AS TEXT), CASE WHEN COUNT(*) = 4 THEN 'pass' ELSE 'fail' END FROM rule_summary
UNION ALL SELECT 'Q25', 'county consequence rows', '56', CAST(COUNT(*) AS TEXT), CASE WHEN COUNT(*) = 56 THEN 'pass' ELSE 'fail' END FROM county_concentration
UNION ALL SELECT 'Q26', 'group consequence rows', '76', CAST(COUNT(*) AS TEXT), CASE WHEN COUNT(*) = 76 THEN 'pass' ELSE 'fail' END FROM group_consequences
UNION ALL SELECT 'Q27', 'group rows per rule', '19 each', CAST(MIN(group_rows) AS TEXT) || ' to ' || CAST(MAX(group_rows) AS TEXT), CASE WHEN MIN(group_rows) = 19 AND MAX(group_rows) = 19 THEN 'pass' ELSE 'fail' END FROM (SELECT rule_id, COUNT(*) group_rows FROM group_consequences GROUP BY rule_id)
UNION ALL SELECT 'Q28', 'suppression rows preserved', '>0', CAST(SUM(selected_suppressed_rows + unselected_suppressed_rows) AS TEXT), CASE WHEN SUM(selected_suppressed_rows + unselected_suppressed_rows) > 0 THEN 'pass' ELSE 'fail' END FROM group_consequences
UNION ALL SELECT 'Q29', 'pairwise rule overlaps', '6', CAST(COUNT(*) AS TEXT), CASE WHEN COUNT(*) = 6 THEN 'pass' ELSE 'fail' END FROM rule_overlap
UNION ALL SELECT 'Q30', 'sensitivity variants', '20', CAST(COUNT(*) AS TEXT), CASE WHEN COUNT(*) = 20 THEN 'pass' ELSE 'fail' END FROM sensitivity_results
UNION ALL SELECT 'Q31', 'base sensitivity variants', '4', CAST(COUNT(*) AS TEXT), CASE WHEN COUNT(*) = 4 AND MIN(actual_selected) = 28 AND MAX(actual_selected) = 28 THEN 'pass' ELSE 'fail' END FROM sensitivity_results WHERE variant_type = 'base'
UNION ALL SELECT 'Q32', 'resource sensitivity variants', '8', CAST(COUNT(*) AS TEXT), CASE WHEN COUNT(*) = 8 THEN 'pass' ELSE 'fail' END FROM sensitivity_results WHERE variant_type = 'resource'
UNION ALL SELECT 'Q33', 'selected order populated', '112', CAST(SUM(selected = 1 AND selection_order IS NOT NULL) AS TEXT), CASE WHEN SUM(selected = 1 AND selection_order IS NOT NULL) = 112 THEN 'pass' ELSE 'fail' END FROM rule_assignments
UNION ALL SELECT 'Q34', 'excluded order empty', '0 invalid', CAST(SUM(selected = 0 AND selection_order IS NOT NULL) AS TEXT), CASE WHEN SUM(selected = 0 AND selection_order IS NOT NULL) = 0 THEN 'pass' ELSE 'fail' END FROM rule_assignments
UNION ALL SELECT 'Q35', 'selected inclusion reason', '112', CAST(SUM(selected = 1 AND inclusion_reason != '') AS TEXT), CASE WHEN SUM(selected = 1 AND inclusion_reason != '') = 112 THEN 'pass' ELSE 'fail' END FROM rule_assignments
UNION ALL SELECT 'Q36', 'excluded reason', '6276', CAST(SUM(selected = 0 AND exclusion_reason != '') AS TEXT), CASE WHEN SUM(selected = 0 AND exclusion_reason != '') = 6276 THEN 'pass' ELSE 'fail' END FROM rule_assignments
UNION ALL SELECT 'Q37', 'one accountable owner', '1', CAST(COUNT(DISTINCT accountable_owner) AS TEXT), CASE WHEN COUNT(DISTINCT accountable_owner) = 1 THEN 'pass' ELSE 'fail' END FROM candidate_release
UNION ALL SELECT 'Q38', 'candidate public role', '1597', CAST(SUM(public_evidence_role = 'accepted public modeled area-level estimate') AS TEXT), CASE WHEN SUM(public_evidence_role = 'accepted public modeled area-level estimate') = 1597 THEN 'pass' ELSE 'fail' END FROM candidate_release
UNION ALL SELECT 'Q39', 'candidate synthetic role', '1597', CAST(SUM(synthetic_planning_role = 'fictional capacity, access, review, objection, and burden conditions') AS TEXT), CASE WHEN SUM(synthetic_planning_role = 'fictional capacity, access, review, objection, and burden conditions') = 1597 THEN 'pass' ELSE 'fail' END FROM candidate_release
UNION ALL SELECT 'Q40', 'claim limits populated', '0 missing', CAST(SUM(interpretation_limit = '') AS TEXT), CASE WHEN SUM(interpretation_limit = '') = 0 THEN 'pass' ELSE 'fail' END FROM rule_assignments
ORDER BY check_id;
