exporter.fhir.export = true
exporter.fhir.bulk_data = true
exporter.fhir.use_us_core_ig = true
exporter.fhir.us_core_version = 7.0.0
exporter.fhir.transaction_bundle = false
exporter.pretty_print = false
exporter.encoding = UTF-8
exporter.years_of_history = 5
exporter.metadata.export = false
exporter.hospital.fhir.export = false
exporter.practitioner.fhir.export = false
exporter.ccda.export = false
exporter.csv.export = false
exporter.json.export = false
generate.only_alive_patients = true
generate.thread_pool_size = 1
generate.log_patients.detail = none
generate.append_numbers_to_person_names = true
